# -*- coding: utf-8 -*-
"""codigo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GknAUkeNS_hlrCbkbDO0F6_1uc2KRy7R
"""

import streamlit as st
from PIL import Image
import pytesseract
from gtts import gTTS
import os
import tempfile
import shutil

# Título de la aplicación
st.title("Convertir Imagen a Audio")

# Cargar una imagen
uploaded_image = st.file_uploader("Cargar una imagen", type=["jpg", "png", "jpeg"])

# Variable para almacenar el texto de la imagen
image_text = ""

# Verificar si se ha cargado una imagen
if uploaded_image is not None:
    # Mostrar la imagen
    image = Image.open(uploaded_image)
    st.image(image, caption="Imagen cargada", use_column_width=True)

    # Botón para extraer texto de la imagen
    if st.button("Extraer Texto"):
        # Utilizar Tesseract para convertir la imagen en texto
        image_text = pytesseract.image_to_string(image)
        st.write("Texto extraído:")
        st.write(image_text)

# Botón para generar audio desde el texto extraído
if image_text:
    if st.button("Generar Audio"):
        # Crear un archivo temporal para guardar el audio
        temp_dir = tempfile.mkdtemp()
        audio_file_path = os.path.join(temp_dir, "output.mp3")

        # Generar el audio a partir del texto
        tts = gTTS(text=image_text, lang="es")
        tts.save(audio_file_path)

        # Reproducir el audio
        st.audio(audio_file_path, format="audio/mp3", start_time=0)

        # Eliminar el archivo temporal después de reproducir el audio
        shutil.rmtree(temp_dir)

# Contenido del archivo requirements.txt
# Debes crear un archivo llamado requirements.txt y copiar esto dentro
# para que se instalen las bibliotecas necesarias.